"""
File: train_gmm.py

This script fits a Gaussian Mixture Model (GMM) to the dimensionality-reduced feature
space. The resulting model serves as a probabilistic clustering mechanism for evaluation
and reward calculation in downstream tasks.
  1. GMMTrainer:
* init: Configures the GMM parameters, including the number of components (clusters), covariance
        type, and multiple initializations (n_init) to ensure the model avoids poor local optima.
* train:    Loads the fused feature matrix generated by the feature pipeline, fits the GMM to
            the data, and verifies whether the Expectation-Maximization algorithm converged successfully.
* save: Uses joblib to serialize and export the fitted GMM object to a .pkl file for use in the
        inference pipeline.
"""


import os
import joblib
import numpy as np
from sklearn.mixture import GaussianMixture

class GMMTrainer:
    """
    Fits a Gaussian Mixture Model to the fused, dimensionality-reduced features.
    Saves the trained model to be used as a reward/evaluation mechanism in the RL environment.
    """
    def __init__(self, n_components=5, covariance_type='spherical', random_state=42):
        self.n_components = n_components
        self.covariance_type = covariance_type
        self.random_state = random_state
        
        self.model = GaussianMixture(
            n_components=self.n_components, 
            covariance_type=self.covariance_type, 
            random_state=self.random_state, 
            n_init=10 # Run 10 times with different initializations to find the best fit
        )

    def train(self, features_path="USL_training/training_features.npy"):
        """Loads the pre-processed numpy array and fits the GMM."""
        print(f"Loading extracted features from: {features_path}")
        if not os.path.exists(features_path):
            raise FileNotFoundError(f"Cannot find {features_path}. Run feature_pipeline.py first.")
            
        X_train = np.load(features_path)
        print(f"Features loaded successfully. Shape: {X_train.shape}")
        
        print(f"Fitting GMM with {self.n_components} components...")
        self.model.fit(X_train)
        
        # Check convergence (good practice for GMMs)
        if self.model.converged_:
            print(f"GMM converged in {self.model.n_iter_} iterations.")
        else:
            print("WARNING: GMM did not converge. Consider increasing max_iter.")
            
        return self.model

    def save(self, save_path="USL_training/gmm_model.pkl"):
        """Saves the fitted GMM artifact for the inference pipeline."""
        os.makedirs(os.path.dirname(save_path), exist_ok=True)
        joblib.dump(self.model, save_path)
        print(f"[Artifact Saved] GMM model successfully saved to: {save_path}")


if __name__ == "__main__":
    # Ensure this matches the exact number of asset classes in your dataset
    TARGET_CLUSTERS = 5 
    
    trainer = GMMTrainer(n_components=TARGET_CLUSTERS)
    
    print("\n=== STARTING GMM TRAINING ===")
    trainer.train(features_path="USL_training/training_features.npy")
    trainer.save(save_path="USL_training/gmm_model.pkl")
    print("=== GMM TRAINING COMPLETE ===\n")